<template>
  <div class="min-h-screen bg-gray-100">
    <!-- Horizontal Navbar -->
    <nav class="fixed top-0 left-0 z-50 w-full bg-white/90 backdrop-blur-md shadow-md">
      <div class="container mx-auto px-4 py-4 flex items-center justify-between">
        <div class="flex items-center space-x-6">
          <NuxtLink to="/" class="text-primary-600 hover:text-primary-800 font-medium transition-colors">
            <i class="fas fa-home mr-2"></i>Home
          </NuxtLink>
          <NuxtLink to="/blog" class="text-primary-600 hover:text-primary-800 font-medium transition-colors">
            <i class="fas fa-blog mr-2"></i>Blog
          </NuxtLink>
        </div>
        <a href="/CV_Vahid_Rahimzadeh_Dec_2025.pdf" download class="px-4 py-2 text-sm bg-primary-600 text-white rounded hover:bg-primary-700 transition-colors">
          <i class="fas fa-download mr-2"></i>Download CV
        </a>
      </div>
    </nav>

    <div class="container mx-auto p-4 pt-24">
      <!-- Disclaimer -->
      <div class="mb-4 p-3 bg-yellow-50 border border-yellow-200 rounded-lg">
        <p class="text-sm text-yellow-800">
          <i class="fas fa-info-circle mr-2"></i>
          <strong>Note:</strong> This is placeholder content generated by AI for demonstration purposes.
        </p>
      </div>

      <!-- Article -->
      <article class="relative p-8 border rounded-lg shadow-md bg-gradient-to-br from-white to-primary-50/50 backdrop-blur-md bg-opacity-70 border-primary-100">
        <div class="circle-deep-green w-60 h-60 rounded-full absolute z-[-1] -top-20 right-0 transform translate-x-1/4"></div>
        <div class="circle-deep-green w-40 h-40 rounded-full absolute z-[-1] bottom-10 left-0 transform -translate-x-1/4"></div>
        
        <div class="relative z-10">
          <!-- Header -->
          <header class="mb-8 pb-6 border-b border-gray-200">
            <h1 class="text-4xl font-bold text-primary-900 mb-4">{{ data?.title }}</h1>
            
            <div class="flex items-center space-x-6 text-sm text-gray-600 mb-4">
              <span><i class="far fa-calendar mr-2"></i>{{ formatDate(data?.date) }}</span>
              <span v-if="data?.readingTime"><i class="far fa-clock mr-2"></i>{{ data.readingTime }}</span>
            </div>
            
            <div v-if="data?.tags && data.tags.length" class="flex flex-wrap gap-2">
              <span 
                v-for="tag in data.tags" 
                :key="tag"
                class="px-3 py-1 text-sm border rounded-md border-primary-200 bg-primary-50 text-primary-700"
              >
                {{ tag }}
              </span>
            </div>
          </header>

          <!-- Content -->
          <div class="prose prose-lg max-w-none">
            <ContentRenderer :value="data" class="nuxt-content" />
          </div>
        </div>
      </article>
    </div>
  </div>
</template>

<script setup>
const route = useRoute()
const { data } = await useAsyncData(`blog-${route.path}`, () => 
  queryContent(route.path).findOne()
)

const formatDate = (date) => {
  if (!date) return ''
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}
</script>

<style>
.nuxt-content h2 {
  @apply text-2xl font-bold text-primary-800 mt-8 mb-4;
}

.nuxt-content h3 {
  @apply text-xl font-semibold text-primary-700 mt-6 mb-3;
}

.nuxt-content p {
  @apply text-gray-800 mb-4 leading-relaxed;
}

.nuxt-content ul,
.nuxt-content ol {
  @apply mb-4 ml-6;
}

.nuxt-content li {
  @apply text-gray-800 mb-2;
}

.nuxt-content a {
  @apply text-primary-600 hover:text-primary-800 underline;
}

.nuxt-content code {
  @apply bg-gray-100 px-2 py-1 rounded text-sm font-mono;
}

.nuxt-content pre {
  @apply bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto mb-4;
}

.nuxt-content pre code {
  @apply bg-transparent p-0;
}

.nuxt-content blockquote {
  @apply border-l-4 border-primary-300 pl-4 italic text-gray-700 my-4;
}
</style>
