<template>
  <div class="min-h-screen bg-gray-100">
    <!-- Horizontal Navbar -->
    <nav class="fixed top-0 left-0 z-50 w-full bg-white/90 backdrop-blur-md shadow-md">
      <div class="container mx-auto px-4 py-4 flex items-center justify-between">
        <div class="flex items-center space-x-6">
          <NuxtLink to="/" class="text-primary-600 hover:text-primary-800 font-medium transition-colors">
            <i class="fas fa-home mr-2"></i>Home
          </NuxtLink>
          <NuxtLink to="/blog" class="text-primary-600 hover:text-primary-800 font-medium transition-colors">
            <i class="fas fa-blog mr-2"></i>Blog
          </NuxtLink>
        </div>
        <a href="/CV_Vahid_Rahimzadeh_Dec_2025.pdf" download class="px-4 py-2 text-sm bg-primary-600 text-white rounded hover:bg-primary-700 transition-colors">
          <i class="fas fa-download mr-2"></i>Download CV
        </a>
      </div>
    </nav>

    <div class="container mx-auto p-4 pt-24">
      <!-- Header -->
      <div class="mb-8">
        <NuxtLink to="/" class="inline-flex items-center text-primary-600 hover:text-primary-800 mb-4">
          <i class="fas fa-arrow-left mr-2"></i>
          Back to Home
        </NuxtLink>
        <h1 class="text-4xl font-bold text-primary-900 mb-2">Blog</h1>
        <p class="text-gray-600">Thoughts, ideas, and insights on AI, research, and technology</p>
        <p class="text-sm text-gray-500 italic mt-2">Note: The blog posts below are placeholder content generated by AI for demonstration purposes.</p>
      </div>

      <!-- Blog Posts Grid -->
      <div v-if="posts && posts.length" class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        <article 
          v-for="post in posts" 
          :key="post._path"
          class="relative p-6 border rounded-lg shadow-md bg-gradient-to-br from-white to-primary-50/50 backdrop-blur-md bg-opacity-70 border-primary-100 transition-all hover:shadow-lg hover:-translate-y-1"
        >
          <NuxtLink :to="post._path" class="flex flex-col h-full">
            <div class="mb-4">
              <h2 class="text-2xl font-bold text-primary-800 mb-2 hover:text-primary-600 transition-colors">
                {{ post.title }}
              </h2>
              <p class="text-gray-700 mb-4 line-clamp-3">
                {{ post.description }}
              </p>
            </div>
            
            <div class="flex-grow"></div>
            
            <div>
              <div v-if="post.tags && post.tags.length" class="flex flex-wrap gap-2 mb-4">
                <span 
                  v-for="tag in post.tags" 
                  :key="tag"
                  class="px-2 py-1 text-xs border rounded-md border-primary-200 bg-primary-50 text-primary-700"
                >
                  {{ tag }}
                </span>
              </div>
              
              <div class="flex items-center justify-between">
                <div class="flex items-center space-x-4 text-sm text-gray-600">
                  <span><i class="far fa-calendar mr-1"></i>{{ formatDate(post.date) }}</span>
                  <span v-if="post.readingTime"><i class="far fa-clock mr-1"></i>{{ post.readingTime }}</span>
                </div>
                <div class="text-primary-600 font-medium hover:text-primary-800">
                  Read more <i class="fas fa-arrow-right ml-1"></i>
                </div>
              </div>
            </div>
          </NuxtLink>
        </article>
      </div>

      <!-- Empty State -->
      <div v-else class="text-center py-12">
        <i class="fas fa-pen-nib text-6xl text-gray-300 mb-4"></i>
        <h2 class="text-2xl font-semibold text-gray-600 mb-2">No posts yet</h2>
        <p class="text-gray-500">Check back soon for new content!</p>
      </div>
    </div>
  </div>
</template>

<script setup>
const { data: posts } = await useAsyncData('blog-posts', () => 
  queryContent('/blog')
    .sort({ date: -1 })
    .find()
)

const formatDate = (date) => {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}
</script>

<style scoped>
.line-clamp-3 {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
